### ISSUE TITLE
Building front fails for version 1.6.4

### ISSUE THREAD

**Issue by gbonnefille** [kosmas58/pia-docker#5]
Running build of the front failed with:

```
warning Error running install script for optional dependency: "/var/www/pia/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /var/www/pia/node_modules/node-sass
Output:
Building: /opt/node-v10.13.0-linux-x64/bin/node /var/www/pia/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/opt/node-v10.13.0-linux-x64/bin/node',
gyp verb cli   '/var/www/pia/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@10.13.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing \"build\" directory
gyp verb command configure []
gyp verb check python checking for Python executable \"python2\" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/pia/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/pia/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/pia/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/pia/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/pia/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/pia/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/pia/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/pia/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/pia/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/pia/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/pia/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/pia/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\\n    at getNotFoundError (/var/www/pia/node_modules/which/which.js:13:12)\\n    at F (/var/www/pia/node_modules/which/which.js:68:19)\\n    at E (/var/www/pia/node_modules/which/which.js:80:29)\\n    at /var/www/pia/node_modules/which/which.js:89:16\\n    at /var/www/pia/node_modules/isexe/index.js:42:5\\n    at /var/www/pia/node_modules/isexe/mode.js:8:5\\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable \"python\" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/var/www/pia/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/pia/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/pia/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/pia/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/pia/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/pia/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/var/www/pia/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/pia/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/pia/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/pia/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/pia/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/pia/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\\n    at getNotFoundError (/var/www/pia/node_modules/which/which.js:13:12)\\n    at F (/var/www/pia/node_modules/which/which.js:68:19)\\n    at E (/var/www/pia/node_modules/which/which.js:80:29)\\n    at /var/www/pia/node_modules/which/which.js:89:16\\n    at /var/www/pia/node_modules/isexe/index.js:42:5\\n    at /var/www/pia/node_modules/isexe/mode.js:8:5\\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable \"python\", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/var/www/pia/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/var/www/pia/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/var/www/pia/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/var/www/pia/node_modules/which/which.js:80:29)
gyp ERR! stack     at /var/www/pia/node_modules/which/which.js:89:16
gyp ERR! stack     at /var/www/pia/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /var/www/pia/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command \"/opt/node-v10.13.0-linux-x64/bin/node\" \"/var/www/pia/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\" \"--verbose\" \"--libsass_ext=\" \"--libsass_cflags=\" \"--libsass_ldflags=\" \"--libsass_library=\"
gyp ERR! cwd /var/www/pia/node_modules/node-sass
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1"
```

**Comment by kosmas58** [comment]
I've merged your commit today.

**Comment by gbonnefille** [comment]
Are you sure? This commit is not merge (yet) and changes are not reported in master branch.
